chat/urls.py
from django.conf.urls import url

from . import views

app_name = 'chat'

urlpatterns = [
	url(r'^get_users_online$', views.get_users_online, name='get_users_online'),
	url(r'^get_chat$', views.get_chat, name='get_chat'),
	url(r'^post_message$', views.post_message, name='post_message'),
]

chat/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class ChatMessage(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    when = models.DateTimeField(auto_now_add=True)
    message = models.CharField(blank=False, null=False, max_length=500)

chat/views.py
import json

from django.utils import timezone
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

#from cloudjangohost.lastSeenMiddleware.models import LastSeen
from .models import ChatMessage

# Create your views here.
@login_required
def get_users_online(request):
    # lastSeens = LastSeen.objects.filter(when__gte=timezone.now() - timezone.timedelta(minutes=1))
    json_dict = {}
    # i = 0
    # for lastSeen in lastSeens:
    #     json_dict[i] = lastSeen.user.username
    #     i += 1
    return JsonResponse(json_dict)

@login_required
def get_chat(request):
    lastID = int(request.POST.get('lastID'))
    if lastID == None:
        return redirect('home:homepage')
    
    if lastID == -1:
        messages = ChatMessage.objects.filter(when__gte=timezone.now() - timezone.timedelta(minutes=30)).order_by('when')
    else:
        lastMessageSent = ChatMessage.objects.get(pk=lastID)
        if lastMessageSent == None:
            return redirect('home:homepage')
        messages = ChatMessage.objects.filter(when__gt=lastMessageSent.when).order_by('when')

    returnID = messages.last().id if messages.last() else lastID
    
    msg_dict = {}
    i = 0
    for message in messages:
        msg_dict[i] = {
            'username': message.user.username,
            'time': message.when.strftime("%m-%d %H:%M:%S"),
            'message': message.message,
        }
        i += 1
    
    json_dict = {'lastID': returnID, 'msg': msg_dict}
    return JsonResponse(json_dict)
    
@login_required
def post_message(request):
    message = request.POST.get('message')
    
    if message:
        ChatMessage(user=request.user, message=message).save()
    return HttpResponse()

chat/templates/chat/chat.html
<div class="card white">
    <div class="card-content" style="height:100vh; overflow-y:auto;">
        <span class="card-title">Chat</span>
        <hr>
		<div class="input-field col s12">
			<textarea id="message" class="materialize-textarea" maxlength="500"></textarea>
			<label for="message">Message</label>
		</div>
		<button class="btn waves-effect waves-light deep-purple darken-4" onclick="submitChat()">Send</button>
		<hr>
		<p id="usersOnline"></p>
		<hr>
		<ul class="collection" id="chat">
		</ul>
    </div>
</div>

chat/templates/chat/chat_js.html
<script type="text/javascript">
var lastID=-1;
window.CSRF_TOKEN = "{{ csrf_token }}";
window.CHAT_USERNAME = "{{ user.username }}";

var col_you = '<li class="collection-item deep-purple lighten-4">';
var col = '<li class="collection-item">';
var left = '<span class="left">';
var mid = '</span><span class="right">';
var mid_br = '</span><br>';
var right = '</li>';

//https://realpython.com/blog/python/getting-started-with-django-channels/
//TODO: implement Django channels later for use with chat and queue
function refreshUsers(){
    $.ajax({
		url: "{% url 'chat:get_users_online' %}",
		type: "POST",
		data: {csrfmiddlewaretoken: window.CSRF_TOKEN},
		success: function(data){
		    document.getElementById("usersOnline").innerHTML = "Online: ";
		    for(key in data){
		        document.getElementById("usersOnline").innerHTML += data[key] + " ";
		    }
		}
	});
}

function refreshChat(){
	$.ajax({
		url: "{% url 'chat:get_chat' %}",
		type: "POST",
		data: {csrfmiddlewaretoken: window.CSRF_TOKEN, lastID: lastID},
		success: function(data){
			if(data)
			{
                lastID=parseInt(data['lastID']);
                for(key in data['msg']){
                	entry = data['msg'][key];
                    if(entry['username'] == window.CHAT_USERNAME)
                        $('#chat').prepend(col_you+left+entry['username']+mid+entry['time']+mid_br+entry['message']+right);
                    else
                        $('#chat').prepend(col+left+entry['username']+mid+entry['time']+mid_br+entry['message']+right);
                }
			}
		}
	});
}

function submitChat(){
	$.ajax({
		url: "{% url 'chat:post_message' %}",
		type: "POST",
		data: {csrfmiddlewaretoken: window.CSRF_TOKEN, message: document.getElementById('message').value},
	});
	document.getElementById('message').value="";
}

function chat_init(user_interval, chat_interval){
    refreshUsers();
    refreshChat();
    setInterval(refreshUsers, user_interval);
    setInterval(refreshChat, chat_interval);
}
</script>