chat/urls.py
from django.conf.urls import url

from . import views

app_name = 'chat'

urlpatterns = [
	url(r'^get_users_online$', views.get_users_online, name='get_users_online'),
	url(r'^get_chat$', views.get_chat, name='get_chat'),
	url(r'^post_message$', views.post_message, name='post_message'),
]

tags/urls.py
from django.conf.urls import url

from . import views

app_name = 'tags'

urlpatterns = [
	url(r'^add_tag$', views.add_tag, name='add_tag'),
	url(r'^get_suggested_tags_json$', views.get_suggested_tags_json, name='get_suggested_tags_json'),
	url(r'^add_suggested_tag$', views.add_suggested_tag, name='add_suggested_tag'),
	url(r'^decline_suggested_tag$', views.add_tag_declination, name='remove_suggested_tag'),
	url(r'^tag_list$', views.tag_list, name='tag_list'),
	url(r'^tag_description/(?P<tag>.*)$', views.tag_description, name='tag_description'),
	url(r'^get_tag_lists$', views.get_tag_lists, name='get_tag_lists'),
]

tags/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

from posts.models import Post

# Create your models here.
class Tag(models.Model):
	name = models.CharField(blank=False, null=False, max_length=64, unique=True)
	tag_type = models.PositiveSmallIntegerField(blank=False, null=False)
	description = models.TextField(blank=False, null=False)
	staff_only = models.BooleanField(default=False, blank=False, null=False)
	min_board = models.PositiveSmallIntegerField(blank=False, null=False)
	posts = models.ManyToManyField(Post, blank=True, editable=False)
	occurences = models.IntegerField(blank=False, null=False, default=0)
	
	def __str__(self):
		return self.name
	
	def increment_occurences(self):
		self.occurences += 1
		self.save(update_fields=['occurences'])
	
	class Meta:
		indexes = [
			models.Index(fields=['name']),
		]
	
class PostTag(models.Model):
	tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	added_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
	date = models.DateTimeField(auto_now_add=True)
	
	class Meta:
		indexes = [
			models.Index(fields=['post', 'tag']),
		]
		
class TagDeclination(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
	
	class Meta:
		indexes = [
			models.Index(fields=['post']),
		]
		unique_together = ("post", "tag")

@receiver(post_save, sender=Tag)
def update_tag_dictionary(sender, instance, created, **kwargs):
	if created:
		tags = Tag.objects.all()
		tag_dict = {}
		i = 0
		for tag in tags:
			tag_dict[i] = tag.name
			i += 1
			
		import json
		from cloudjangohost.settings import TAG_DICT_PATH
		with open(TAG_DICT_PATH, 'w') as fp:
			json.dump(tag_dict, fp)

tags/views.py
from ast import literal_eval
import socket

from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import F
from django.db.models import Q

from posts.models import Post
from .models import Tag, PostTag, TagDeclination
from .objects import TaggablePost

from cloudjangohost.settings import NEURAL_SUGGEST_SOCKET

# Create your views here.

@login_required
def tag_list(request):
	context = {
		'tags': Tag.objects.order_by('name').values_list('name', flat=True),
	}
	return render(request, 'tags/tag_list.html', context)

@login_required
def tag_description(request, tag):
	tag = get_object_or_404(Tag, name=tag)
	all_tag_ids = list(Tag.objects.values_list('id', flat=True))
	context = {
		'tag': tag,
		'chancesFrom': [],
		'chancesTo': get_tag_set_predictions([tag.id], all_tag_ids),
	}
	return render(request, 'tags/tag.html', context)

@login_required
def add_tag(request):
	TaggablePost(request.POST.get('filename'), request.user.pk).add_tag(request.POST.get('tag'))
	return redirect('posts:post', board=request.POST.get('board'), filename=request.POST.get('filename'))
	
@login_required
def add_suggested_tag(request):
	TaggablePost(request.POST.get('filename'), request.user.pk).add_tag(request.POST.get('tag'))
	return HttpResponse()

@login_required
def add_tag_declination(request):
	TaggablePost(request.POST.get('filename'), request.user.pk).add_tag_declination(request.POST.get('tag'))
	return HttpResponse()

@login_required
def get_suggested_tags_json(request):
	post = get_object_or_404(Post, filename=request.POST.get('filename'))
	tPost = TaggablePost(request.POST.get('filename'), None)

	tags = tPost.get_tag_list()
	tags_to_predict = tPost.get_possible_tag_list()
	
	sug_list = get_tag_set_predictions(tags, tags_to_predict)
	sug_dict = {k: sug_list[k] for k in range(len(sug_list))}
	return JsonResponse(sug_dict)
	
def get_tag_set_predictions(tag_ids_set, tag_ids_to_predict):
	s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	s.connect(('localhost', NEURAL_SUGGEST_SOCKET))
	s.sendall(str(tag_ids_set).encode('utf-8'))
	s.shutdown(socket.SHUT_WR)
	msg=[]
	while True:
		data = s.recv(8192)
		if not data: break
		msg.append(data.decode('utf-8'))
	predicts = literal_eval(''.join(msg))
	sug_list = []
	for tag in tag_ids_to_predict:
		sug_list.append({
			'name': Tag.objects.get(id=tag).name,
			'percent': predicts[tag]*100
		})
	sug_list = sorted(sug_list, key=lambda k: k['percent'], reverse=True) 
	return sug_list
	
def get_tag_lists(request):
	#Used to get a list of lists, where each list are all tags of a post
	#Will be used to parse neural network data on another machine
	from cloudjangohost.settings import TAG_API_KEY
	key = request.GET.get('key')
	if not key == TAG_API_KEY:
		return JsonResponse({})
	posts = Post.objects.all()
	all_tags = set(list(Tag.objects.all().values_list('id', flat=True)))
	p = []
	p2 = []
	for post in posts:
		tPost = TaggablePost(post, None)
		if post.tag_set.exists():
			p.append(tPost.get_tag_list())
			p2.append(tPost.get_tag_declination_list())
	ret = {
		'lists': p,
		'lists_dec': p2,
		'count': Tag.objects.count()
	}
	return JsonResponse(ret)

tags/templates/tags/suggestedTags.html
<!-- Include this and add $('#sug_button').click(getSugTags) to some button
or just call getSugTags in some other way
-->
<div id="sug_tags">
</div>
<script type="text/javascript">
//AJAX fetch the suggestions when suggested tags are opened
	got_sugs = false;
	function getSugTags(){
		if(got_sugs) return;
	    $.ajax({
			url: "{% url 'tags:get_suggested_tags_json' %}",
			type: "POST",
			data: {csrfmiddlewaretoken: window.CSRF_TOKEN, filename: "{{ post.filename }}"},
			success: function(data){
				if(data) for(key in data){
					id = 'sug_tag_'+key;
					a_id = 't_a_'+key;
					r_id = 't_r_'+key;
					$('#sug_tags').append(
						'<div id="'+id+'" class="card grey darken-4">'+
						'<div class="card-content" style="word-break: break-all; padding: 10px;">'+data[key]['percent']+'%<br>'+data[key]['name']+'</div>'+
						'<div class="card-action">'+
						'<i id="'+a_id+'" class="material-icons green-text" style="cursor: pointer;">check</i>'+
						'<i id="'+r_id+'" class="material-icons red-text" style="cursor: pointer;">clear</i>'+
						'</div></div>'
					);
					$('#'+r_id).bind("click", {tag: data[key]['name'], id: id}, removeSug);
					$('#'+a_id).bind("click", {tag: data[key]['name'], id: id}, addSug);
				}
				got_sugs=true;
			}
		});
	}
	function addSug(event){
		d = event.data;
		$.ajax({
			url: "{% url 'tags:add_suggested_tag' %}",
			type: "POST",
			data: {csrfmiddlewaretoken: window.CSRF_TOKEN, tag: d.tag, filename: "{{ post.filename }}"},
		});
		document.getElementById(d.id).outerHTML='';
	}
	function removeSug(event){
		d = event.data;
		$.ajax({
			url: "{% url 'tags:remove_suggested_tag' %}",
			type: "POST",
			data: {csrfmiddlewaretoken: window.CSRF_TOKEN, tag: d.tag, filename: "{{ post.filename }}"},
		});
		document.getElementById(d.id).outerHTML='';
	}
</script>

tags/templates/tags/tag.html
{% extends 'base_nav.html' %}

{% block title %} Tag {% endblock %}

{% block jsFunctions %}

{% endblock %}

{% block jsInit %}

{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="card">
			<div class="card-content">
				<span class="card-title">{{ tag.name }}</span>
				<p>{{ tag.description }}</p>
				<p>Type: {{tag.tag_type}}</p>
				<p>Min board: {{tag.min_board}}</p>
				<p>Staff only: {{tag.staff_only}}</p>
				<p>Times used: {{ tag.occurences }}</p>
				<hr>
				<div class="row">
					<div class="col s12 m6">
						<h5>Implied by:</h5>
						{% for c in chancesFrom %}
							<p>{{ c.percent }}% -- {{ c.name }}</p>
						{% endfor %}
					</div>
					<div class="col s12 m6">
						<h5>Implies:</h5>
						{% for c in chancesTo %}
							<p>{{ c.percent }}% -- {{ c.name }}</p>
						{% endfor %}
					</div>
				</div>
			</div>
	    </div>
    </div>
</div>
{% endblock %}

tags/templates/tags/tag_list.html
{% extends 'base_nav.html' %}

{% block title %} Tags List {% endblock %}

{% block jsFunctions %}
<script>

</script>
{% endblock %}

{% block jsInit %}
<script type="text/javascript">
    function init(){

	}
</script>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col s12">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">Tags</span>
                    <div class="row">
                        {% for tag in tags %}
                            <a class="col s12 m6 l3" href="{% url 'tags:tag_description' tag=tag %}">{{ tag }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}