chat/urls.py
from django.conf.urls import url

from . import views

app_name = 'chat'

urlpatterns = [
	url(r'^get_users_online$', views.get_users_online, name='get_users_online'),
	url(r'^get_chat$', views.get_chat, name='get_chat'),
	url(r'^post_message$', views.post_message, name='post_message'),
]

downloader/urls.py
from django.conf.urls import url

from . import views

app_name = 'downloader'

urlpatterns = [
	url(r'^queue$', views.queue, name='queue'),
	url(r'^extra/(?P<board>[1-5]{1})/(?P<filename>[0-9a-f]{16})$', views.extra, name='extra'),
	url(r'^submit_extra/(?P<board>[1-5]{1})/(?P<filename>[0-9a-f]{16})$', views.submit_extra, name='submit_extra'),
]

submit/urls.py
from django.conf.urls import url

from . import views

app_name = 'submit'

urlpatterns = [
	url(r'^$', views.submit, name='submit'),
	url(r'^api$', views.submit_api, name='submit_api'),
	url(r'^query_youtube$', views.query_youtube, name='query_youtube'),
	url(r'^query_imgur$', views.query_imgur, name='query_imgur'),
]

submit/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

submit/views.py
import logging

from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

from downloader.helpers import submit_type_is_valid, get_youtube_formats, get_imgur_images
from downloader.operations import submit_url, submit_upload, submit_youtube, submit_imgur
from home.views import get_user_by_api_key

# Create your views here.
@login_required
def submit(request):
    if request.method == "POST":
        submit_type = request.POST.get('submit_type')
        if not submit_type_is_valid(submit_type):
            return render(request, 'submit/index.html', { 'err': 'Invalid submission type selected. Are you hacking?' })
        
        try:
            if 'url' == submit_type:
                submit_url(request)
            elif 'youtube' == submit_type:
                submit_youtube(request)
            elif 'imgur' == submit_type:
                submit_imgur(request)
            return redirect('downloader:queue')
        except Warning as w:
            logging.warning(w, exc_info=True)
            return render(request, 'submit/index.html', { 'err': 'Failed: '+str(w) })
        except Exception as e:
            logging.exception(e)
            return render(request, 'submit/index.html', { 'err': 'Failed: internal server error occured' })
            
        if 'upload' == submit_type:
            #Upload is done with AJAX, so HttpResponses are returned
            try:
                response = submit_upload(request)
            except Warning as w:
                logging.warning(w, exc_info=True)
                return HttpResponse(content='Failed: '+str(w), status=400)
            except Exception as e:
                logging.exception(e)
                return HttpResponse(content='Failed: internal server error occured', status=500)
            return HttpResponse(content=response)
    
    return render(request, 'submit/index.html', None)

@csrf_exempt
def submit_api(request):
    user = get_user_by_api_key(request.POST.get("key"))
    if user:
        request.user = user
        ret = submit(request)
        if isinstance(ret, HttpResponseRedirect):
            return HttpResponse("Success")
        else:
            return HttpResponse("", status=400)
    else:
        return HttpResponse("", status=403)

@csrf_exempt
def query_youtube(request):
    url = request.POST.get('url')
    return JsonResponse(get_youtube_formats(url))
    
@csrf_exempt
def query_imgur(request):
    url = request.POST.get('url')
    return JsonResponse({ 'images': get_imgur_images(url) })

submit/templates/submit/imgur_js.html
<script>
	function queryImgur(){
		CSRF_TOKEN = "{{ csrf_token }}";
		document.getElementById("imgur_types").innerHTML=`
<div class="row center">
	<div class="preloader-wrapper big active">
		<div class="spinner-layer spinner-blue-only">
			<div class="circle-clipper left">
				<div class="circle"></div>
			</div>
			<div class="gap-patch">
				<div class="circle"></div>
			</div>
			<div class="circle-clipper right">
				<div class="circle"></div>
			</div>
		</div>
	</div>
</div>`;
		$.ajax({
			url: "{% url 'submit:query_imgur' %}",
			type: 'POST',
			data: {"url": document.getElementById("imgur_url").value, "csrfmiddlewaretoken": CSRF_TOKEN},
			async: true,
			success: function (data) {
				document.getElementById("imgur_types").innerHTML=`
<h5>Image List</h5>
<a id="imgur_check" class="waves-effect waves-light deep-purple darken-4 btn">Check all</a>
<a id="imgur_clear" class="waves-effect waves-light deep-purple darken-4 btn">Clear all</a>
<table>
	<thead>
		<tr>
			<th>Select</th>
			<th>Image</th>
		</tr>
	</thead>
	<tbody id='imgur_list'>
	</tbody>
</table>
`;
				var img_str = '';
				for(var id in data['images']){
					item = data['images'][id]
					img_str +=`
<tr>
	<td>
		<p>
			<input name="`+item['id']+`" type="checkbox" id="imgur_check`+item['id']+`" class="imgur_check_item"/>
			<label for="imgur_check`+item['id']+`"></label>
		</p>
	</td>
	<td><img class="thumb" src="`+item['url']+`"/></td>
</tr>`;
				}
				document.getElementById("imgur_list").innerHTML = img_str;
				$("#imgur_check").click(checkAll);
				$("#imgur_clear").click(clearAll);
			}
		});
	}
	
	function checkAll(){
		$('.imgur_check_item').each(function(i, obj) {
			$(this).prop('checked', true);
		});
	}
	function clearAll(){
		$('.imgur_check_item').each(function(i, obj) {
			$(this).prop('checked', false);
		});
	}
</script>

submit/templates/submit/index.html
{% extends 'base_nav.html' %}

{% block title %} Submit {% endblock %}

{% block jsFunctions %}
{% include 'submit/upload_js.html' %}
{% include 'submit/youtube_js.html' %}
{% include 'submit/imgur_js.html' %}

<script type="text/javascript">
function setActiveUrl(url){
    var submit_url_ids = ["url_url", "youtube_url", "imgur_url"];
    for(var url_id of submit_url_ids){
        document.getElementById(url_id).name = url_id;
    }
    document.getElementById(url).name = "url";
}
</script>
{% endblock %}

{% block jsInit %}
<script type="text/javascript">
    function init(){
        $("#subForm").submit(function(e){
            if(document.getElementById('submit_type').value == 'upload')
            {
                e.preventDefault();
			    upload(new FormData($(this)[0]), "file");
			    return false;
            }
            else return true;
		});
		$("#youtube_query_btn").click(queryYoutube);
		$("#imgur_query_btn").click(queryImgur);
	}
</script>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col s8">
            <div class="card white">
                <div class="card-content">
                    <form id="subForm" action="{% url 'submit:submit' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        
                        <span class="card-title">Submit</span>
                        <hr>
                        
                        
                        <div class="row">
                            <!-- radio button, lol, start-->
                            <div class="valign-wrapper">
                                <div class="col">
                                    <ul class="tabs">
                                        <li class="tab"><a href="#" onclick="$('#board_radio').val('1');">S</a></li>
                                        <li class="tab"><a href="#" onclick="$('#board_radio').val('2');">G</a></li>
                                        <li class="tab"><a href="#" onclick="$('#board_radio').val('3');" class="active">R</a></li>
                                        <li class="tab"><a href="#" onclick="$('#board_radio').val('4');">X</a></li>
                                    </ul>
                                    <input id="board_radio" type="text" name="board" value="3" autocomplete='off' hidden>
                                </div>
                                <div class="col">
                                    <input type="checkbox" id="private" name="private" />
                                    <label for="private">Private</label>
                                </div>
                            </div>
                            <!-- radio button, lol, end-->
                            <div class="input-field col s12">
                                <i class="material-icons prefix">title</i>
                                <input id="title" name="title" type="text" autocomplete='off'>
                                <label for="title">Title, optional for videos, images</label>
                            </div>
                        </div>
                        
                        
                        <div class="row">
                            <div class="col s12">
                                <ul class="tabs tabs-fixed-width">
                                    <li class="tab col s3"><a href="#url" onclick="$('#submit_type').val('url');setActiveUrl('url_url')" class="active">URL</a></li>
                                    <li class="tab col s3"><a href="#imgur" onclick="$('#submit_type').val('imgur');setActiveUrl('imgur_url')">Imgur</a></li>
                                    <li class="tab col s3"><a href="#youtube" onclick="$('#submit_type').val('youtube');setActiveUrl('youtube_url')">Youtube</a></li>
                                    <li class="tab col s3"><a href="#upload" onclick="$('#submit_type').val('upload');">Upload</a></li>
                                    <li class="tab col s3 disabled"><a href="#website">Website</a></li>
                                </ul>
                            </div>
                            <input id="submit_type" type="text" name="submit_type" value="url" autocomplete='off' hidden>
                        </div>
                        
                        
                        <div id="url">
                            <div class="row">
                                <div class="input-field col s12">
                                    <i class="material-icons prefix">open_in_browser</i>
                                    <input id="url_url" name="url" type="text" autocomplete='off'>
                                    <label for="url_url">Paste URL</label>
                                </div>
                            </div>
                        </div>
                        <div id="imgur">
                            <div class="row">
                                <!-- haxxxor stuff -->
                                <div class="file-field input-field">
                                    <div id="imgur_query_btn" class="btn waves-effect waves-light deep-purple darken-4">
                                        <span>Query Imgur</span>
                                    </div>
                                    <div class="file-path-wrapper">
                                        <input id="imgur_url" name="imgur_url" class="file-path" type="text" autocomplete='off'>
                                    </div>
                                </div>
                            </div>
                            <div id="imgur_types"></div>
                            <div class="row">
                                <ul class="tabs">
                                    <li class="tab"><a href="#" onclick="$('#imgur_type').val('separate');">Separate</a></li>
                                    <li class="tab"><a href="#" onclick="$('#imgur_type').val('album');" class="active">As Album</a></li>
                                </ul>
                                <input id="imgur_type" type="text" name="imgur_type" value="album" autocomplete='off' hidden>
                            </div>
                        </div>
                        <div id="youtube">
                            <div class="row">
                                <!-- haxxxor stuff -->
                                <div class="file-field input-field">
                                    <div id="youtube_query_btn" class="btn waves-effect waves-light deep-purple darken-4">
                                        <span>Query URL</span>
                                    </div>
                                    <div class="file-path-wrapper">
                                        <input id="youtube_url" name="youtube_url" class="file-path" type="text" autocomplete='off'>
                                    </div>
                                </div>
                            </div>
                            <div id="youtube_types"></div>
                            <div class="row">
                                <ul class="tabs">
                                    <li class="tab"><a href="#" onclick="$('#youtube_type').val('music');">Music</a></li>
                                    <li class="tab"><a href="#" onclick="$('#youtube_type').val('video');" class="active">Video</a></li>
                                </ul>
                                <input id="youtube_type" type="text" name="youtube_type" value="video" autocomplete='off' hidden>
                            </div>
                        </div>
                        <div id="upload">
                            <div class="row">
                                <div class="file-field input-field">
                                    <div class="btn waves-effect waves-light deep-purple darken-4">
                                        <span>File</span>
                                        <input type="file" name="file" autocomplete='off'>
                                    </div>
                                    <div class="file-path-wrapper">
                                        <input class="file-path validate" type="text" autocomplete='off'>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div id='upload_status' class="col s4 left-align">Status</div>
                                <div id='upload_percent' class="col s4 center-align">Percent</div>
                                <div id='upload_speed' class="col s4 right-align">Speed</div>
                            </div>
                            <div class="progress">
                                <div id='upload_bar' class="determinate" style="width: 0%"></div>
                            </div>
                        </div>
                        <div id="website">Test 4</div>
                        
                        
                        <button class="btn waves-effect waves-light deep-purple darken-4" type="submit">Submit</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col s4">
            <div class="card white">
                <div class="card-content">
                    <span class="card-title">Info</span>
                    <hr>
                    {% if err %}
                        <p>{{ err }}</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

submit/templates/submit/upload_js.html
<script type="text/javascript">
window.CSRF_TOKEN = "{{ csrf_token }}";

var chunkSize = 1024*1024*64;//64mb
var ubar, ustatus, upercent, uspeed;

var totalChunks;
var identifier;
var fileName;
var fileSize;
var privatePost;
var board;
var title;

var timeUpdated;

function upload(formData, fileIndex)
{
	ubar = document.getElementById("upload_bar");
	ustatus = document.getElementById("upload_status");
	upercent = document.getElementById("upload_percent");
	uspeed = document.getElementById("upload_speed");

	privatePost = formData.get("private");
	board = formData.get("board");
	title = formData.get("title");
	
	fileName = formData.get(fileIndex).name;
	fileSize = formData.get(fileIndex).size;
	totalChunks = Math.ceil(fileSize/chunkSize);
	
	if(totalChunks==0){
		ustatus.innerHTML = "Please select a file";
		return;
	}
	
	ustatus.innerHTML = "Setting up";
	identifier = setupAndGetID();
	if(identifier == "ERR") return;

	ustatus.innerHTML="Uploading";
	uploadPart(formData, fileIndex, 0);
}
function uploadPart(formData, fileIndex, partNum){
	var filePart = getPart(formData, fileIndex, partNum);

	var dataPack = new FormData();
	dataPack.append("chunkNum", partNum);
	dataPack.append("chunk", filePart);
	dataPack.append("uploadID", identifier);
	dataPack.append("csrfmiddlewaretoken", window.CSRF_TOKEN);
	dataPack.append("submit_type", "upload");
	if(partNum+1==totalChunks){
		dataPack.append("lastChunk", 1);
	}

	timeUpdated = (new Date()).getTime();
	//send data package
	$.ajax({
		xhr: function() {
			var xhr = new window.XMLHttpRequest();
			xhr.upload.addEventListener("progress", function(evt) {
				var speed = ((evt.loaded / Math.max(1, (new Date()).getTime() - timeUpdated))*1000) / (1024*1024);

				var pg  = Math.ceil(((partNum+(evt.loaded/evt.total))*100) / totalChunks);
				ubar.style.width = pg+"%";
				upercent.innerHTML = pg+"%"
				uspeed.innerHTML = speed.toFixed(1)+" Mbps";
				if(pg==100){
					ustatus.innerHTML = "File transfered, please wait";
				}
			}, false);
			return xhr;
		},
		url: "{% url 'submit:submit' %}",
		type: 'POST',
		data: dataPack,
		async: true,
		success: function (data) {
			if(partNum+1!=totalChunks)uploadPart(formData, fileIndex, partNum+1);
			else window.location.replace("{% url 'downloader:queue' %}");
		},
		error: function (data){
			ustatus.innerHTML = data.responseText;
		},
		cache: false,
		processData: false,
		contentType: false
	});
}

function getPart(formData, fileIndex, partNum){
	var fileSize = formData.get(fileIndex).size;
	var totalChunks = Math.ceil(fileSize/chunkSize);

	var startByte = partNum*chunkSize;
	var endByte = Math.min(startByte+chunkSize, fileSize);

	if(partNum>=totalChunks) return null;
	return formData.get(fileIndex).slice(startByte, endByte);
}

function setupAndGetID(){
	var dataPack = new FormData();
	dataPack.append("filename", fileName);
	dataPack.append("filesize", Math.ceil(fileSize/1024));
	dataPack.append("chunkNum", -1);
	dataPack.append("private", privatePost);
	dataPack.append("board", board);
	dataPack.append("title", title);
	dataPack.append("csrfmiddlewaretoken", window.CSRF_TOKEN);
	dataPack.append("submit_type", "upload");

	var aj = $.ajax({
		url: "{% url 'submit:submit' %}",
		type: 'POST',
		data: dataPack,
		async: false,
		error: function (data){
			ustatus.innerHTML = data.responseText;
		},
		cache: false,
		processData: false,
		contentType: false
	});

	if(aj.status == 200) return aj.responseText;
	else return "ERR";
}
</script>

submit/templates/submit/youtube_js.html
<script>
	function queryYoutube(){
		CSRF_TOKEN = "{{ csrf_token }}";
		document.getElementById("youtube_types").innerHTML=`
<div class="row center">
	<div class="preloader-wrapper big active">
		<div class="spinner-layer spinner-blue-only">
			<div class="circle-clipper left">
				<div class="circle"></div>
			</div>
			<div class="gap-patch">
				<div class="circle"></div>
			</div>
			<div class="circle-clipper right">
				<div class="circle"></div>
			</div>
		</div>
	</div>
</div>`;
		$.ajax({
			url: "{% url 'submit:query_youtube' %}",
			type: 'POST',
			data: {"url": document.getElementById("youtube_url").value, "csrfmiddlewaretoken": CSRF_TOKEN},
			async: true,
			success: function (data) {
				document.getElementById("youtube_types").innerHTML=`
<h5>Video List</h5>
<table>
	<thead>
		<tr>
			<th>Select</th>
			<th>Extension</th>
			<th>Resolution</th>
			<th>FPS</th>
			<th>Bitrate</th>
			<th>Size</th>
			<th>Codec</th>
		</tr>
	</thead>
	<tbody id='video_list'>
	</tbody>
</table>
<h5>Audio List</h5>
<table>
	<thead>
		<tr>
			<th>Select</th>
			<th>Extension</th>
			<th>Bitrate</th>
			<th>Sampling</th>
			<th>Size</th>
			<th>Codec</th>
		</tr>
	</thead>
	<tbody id='audio_list'>
	</tbody>
</table>`;
				var audio_list = document.getElementById("audio_list");
				var vid_str = '';
				for(var id in data['video']){
					item = data['video'][id]
					vid_str +=`
<tr class="`+item['ext']+`">
	<td>
		<p>
			<input name="video" type="radio" id="youtube_radio`+item['format_id']+`" value="`+item['format_id']+`"/>
			<label onclick='validateFormat("`+item['ext']+`")' for="youtube_radio`+item['format_id']+`"></label>
		</p>
	</td>
	<td>`+item['ext']+`</td>
	<td>`+item['resolution']+`</td>
	<td>`+item['fps']+`</td>
	<td>`+item['bitrate']+`</td>
	<td>`+item['filesize']+`</td>
	<td>`+item['codec']+`</td>
</tr>`;
				}
				document.getElementById("video_list").innerHTML = vid_str;
				var aud_str = '';
				for(var id in data['audio']){
					item = data['audio'][id]
					aud_str +=`
<tr class="`+item['ext']+`">
	<td>
		<p>
			<input name="audio" type="radio" id="youtube_radio`+item['format_id']+`" value="`+item['format_id']+`"/>
			<label onclick='validateFormat("`+item['ext']+`")' for="youtube_radio`+item['format_id']+`"></label>
		</p>
	</td>
	<td>`+item['ext']+`</td>
	<td>`+item['bitrate']+`</td>
	<td>`+item['sampling']+`</td>
	<td>`+item['filesize']+`</td>
	<td>`+item['codec']+`</td>
</tr>`;
				}
				document.getElementById("audio_list").innerHTML = aud_str;
			}
		});
	}
	function validateFormat(className)
	{
		if(className == "webm"){
			var dark = document.getElementsByClassName("webm");
			var grey = document.querySelectorAll('.mp4,.m4a');
		}
		else{
			var grey = document.getElementsByClassName("webm");
			var dark = document.querySelectorAll('.mp4,.m4a');
		}
		for(var i=0, il = dark.length; i<il; i++){
			dark[i].style.color = "";
		}
		for(var i=0, il = grey.length; i<il; i++){
			grey[i].style.color = "LightGray";
			grey[i].childNodes[1].childNodes[1].childNodes[1].checked = false;
		}
	}
</script>