chat/urls.py
from django.conf.urls import url

from . import views

app_name = 'chat'

urlpatterns = [
	url(r'^get_users_online$', views.get_users_online, name='get_users_online'),
	url(r'^get_chat$', views.get_chat, name='get_chat'),
	url(r'^post_message$', views.post_message, name='post_message'),
]

home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'

urlpatterns = [
	url(r'^$', views.homepage, name='homepage'),
	url(r'^profile$', views.profile, name='profile'),
]

posts/urls.py
from django.conf.urls import url

from . import views

app_name = 'posts'

urlpatterns = [
	url(r'^(?P<board>[1-5])/(?P<page>[0-9]+)$', views.show_posts, name='posts'),
	url(r'^post/(?P<board>[1-5]{1})/(?P<filename>[0-9a-f]{16})$', views.show_post, name='post'),
]

submit/urls.py
from django.conf.urls import url

from . import views

app_name = 'submit'

urlpatterns = [
	url(r'^$', views.submit, name='submit'),
	url(r'^api$', views.submit_api, name='submit_api'),
	url(r'^query_youtube$', views.query_youtube, name='query_youtube'),
	url(r'^query_imgur$', views.query_imgur, name='query_imgur'),
]

tags/urls.py
from django.conf.urls import url

from . import views

app_name = 'tags'

urlpatterns = [
	url(r'^add_tag$', views.add_tag, name='add_tag'),
	url(r'^get_suggested_tags_json$', views.get_suggested_tags_json, name='get_suggested_tags_json'),
	url(r'^add_suggested_tag$', views.add_suggested_tag, name='add_suggested_tag'),
	url(r'^decline_suggested_tag$', views.add_tag_declination, name='remove_suggested_tag'),
	url(r'^tag_list$', views.tag_list, name='tag_list'),
	url(r'^tag_description/(?P<tag>.*)$', views.tag_description, name='tag_description'),
	url(r'^get_tag_lists$', views.get_tag_lists, name='get_tag_lists'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>
            {% block title %} Title Here {% endblock %} | Sorc278Host
        </title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        {% load static %}
        <!-- Materialize css -->
        <link href="{% static 'css/materialize.css' %}" rel="stylesheet"/ type="text/css">
        <!-- Materialize icons css -->
        <link href="{% static 'css/icons.css' %}" rel="stylesheet"/ type="text/css">
        <!-- Awesomplete css -->
        <link href="{% static 'css/awesomplete.css' %}" rel="stylesheet"/ type="text/css">
        <!-- Custom CSS -->
        <link href="{% static 'css/cloudHost.css' %}" rel="stylesheet"/ type="text/css">
        
        <!-- jQuery -->
        <script src="{% static 'js/jquery.js' %}"></script>
        <!-- Materialize JavaScript -->
        <script src="{% static 'js/materialize.min.js' %}"></script>
        <!-- Awesomplete suggestions -->
        <script src="{% static 'js/awesomplete.min.js' %}" async></script>
        
        {% block extraHrefs %}{% endblock %}
        
        {% block jsFunctions %}{% endblock %}
        
        {% block jsInit %}
            <script type="text/javascript">function init(){}</script>
        {% endblock %}
    </head>
    <body onload="init()">
        {% block nav %}{% endblock %}
        {% block content %}{% endblock %}
    </body>
</html>

templates/base_nav.html
{% extends 'base.html' %}

{% block title %} Title Here {% endblock %}

{% block extraHrefs %}{% endblock %}

{% block jsFunctions %}{% endblock %}

{% block jsInit %}
    <script type="text/javascript">function init(){}</script>
{% endblock %}

{% block nav %}
<!-- Dropdown Structure -->
<ul id="otherDropdown" class="dropdown-content">
    <li><a href="{% url 'home:profile' %}">Profile</a></li>
    <li><a href=".">Request Tag</a></li>
    <li><a href="{% url 'tags:tag_list' %}">Tag List</a></li>
    <li><a href="{% url 'scratchpad:show_notes' %}">Scratchpad</a></li>
    <li><a href=".">Radio</a></li>
    <li><a href="{% url 'downloader:queue' %}">Queue</a></li>
</ul>
{% if user.is_staff %}
<ul id="adminDropdown" class="dropdown-content">
    <li><a href=".">Storage</a></li>
</ul>
{% endif %}
<nav class="purple darken-4">
    <div class="container">
        <div class="nav-wrapper">
            <a href="{% url 'home:homepage' %}" class="brand-logo">Sorc278 CloudHost</a>
            <a href="#" data-activates="mobileMenu" class="button-collapse"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
                <li><a href="{% url 'submit:submit' %}">Submit</a></li>
                <li><a href="#!">Posts</a></li>
                <li><a href="{% url 'posts:posts' board=1 page=1 %}"><span class="bigLetter">S</span></a></li>
                <li><a href="{% url 'posts:posts' board=2 page=1 %}"><span class="bigLetter">G</span></a></li>
                <li><a href="{% url 'posts:posts' board=3 page=1 %}"><span class="bigLetter">R</span></a></li>
                <!-- Dropdown Trigger -->
                <li><a class="dropdown-button" data-activates="otherDropdown">Other<i class="material-icons right">arrow_drop_down</i></a></li>
                {% if user.is_staff %}
                    <li><a class="dropdown-button" data-activates="adminDropdown">Admin<i class="material-icons right">arrow_drop_down</i></a></li>
                {% endif %}
                <li><a href="{% url 'welcome:logout' %}">Log Out</a></li>
            </ul>
            <ul class="side-nav" id="mobileMenu">
                <li><a href="{% url 'submit:submit' %}">Submit</a></li>
                <li><a href="#!">Posts</a></li>
                <li><a href="{% url 'posts:posts' board=1 page=1 %}"><span class="bigLetter">S</span></a></li>
                <li><a href="{% url 'posts:posts' board=2 page=1 %}"><span class="bigLetter">G</span></a></li>
                <li><a href="{% url 'posts:posts' board=3 page=1 %}"><span class="bigLetter">R</span></a></li>
                <ul class="collapsible collapsible-accordian">
                    <li>
                        <a class="collapsible-header waves-effect">Other<i class="material-icons right">arrow_drop_down</i></a>
                        <div class="collapsible-body">
                            <ul>
                                <li><a href="{% url 'home:profile' %}">Profile</a></li>
                                <li><a href=".">Request Tag</a></li>
                                <li><a href="{% url 'tags:tag_list' %}">Tag List</a></li>
                                <li><a href="{% url 'scratchpad:show_notes' %}">Scratchpad</a></li>
                                <li><a href=".">Radio</a></li>
                                <li><a href="{% url 'downloader:queue' %}">Queue</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
                {% if user.is_staff %}
                <ul class="collapsible collapsible-accordian">
                    <li>
                        <a class="collapsible-header waves-effect">Admin<i class="material-icons right">arrow_drop_down</i></a>
                        <div class="collapsible-body">
                            <ul>
                                <li><a href=".">Storage</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
                {% endif %}
                <li><a href="{% url 'welcome:logout' %}">Log Out</a></li>
            </ul>
        </div>
    </div>
</nav>
<script>
    $(document).ready(function(){
        $(".button-collapse").sideNav();
        $(".dropdown-button").dropdown();
    });
</script>
{% endblock %}

{% block content %}{% endblock %}